name: cache_check

on:
  push:

jobs:
  cache_check:
    name: CacheCheck
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: make permission denied directory
        run: |
          mkdir deniedDir
          cp package-lock.json deniedDir
          chmod 000 deniedDir

      - name: hashFiles
        run: |
          echo "${{ hashFiles('**/package-lock.json') }}"